# Generated by Django 3.2 on 2021-08-11 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20, verbose_name='お名前')),
                ('reserve_date', models.DateTimeField(verbose_name='予約日時')),
                ('contents', models.CharField(blank=True, choices=[('車検', '車検'), ('修理', '修理'), ('その他', 'その他')], default=0, max_length=5, verbose_name='予約内容')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='備考')),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='reserving.reserve', verbose_name='予約')),
            ],
        ),
    ]
